### ISSUE TITLE
Feature tracking

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/workforce#57]
- [ ] Shift types (e.g., Early, Late, Long Day, Night, Office day, Day off), their durations (unit: hours and minutes), start time, end time. Last two are only for display, solver doesn't need to know.
- [ ] Planning horizon in terms of number of weeks (e.g. 4 or 5)
- [ ] List of teams (e.g. Heather and Thistle)
- [ ] List of roles (e.g. Team leader, Senior nurse, Assistant nurse)
- [ ] List of people
    - Name
    - Team
    - Role
    - Contracted work hours per week (unit: hours and minutes) 
    - Allowed shift types (multiselect)
- [ ] Staffing minimums
    - Minimum number of people required for a selected set of teams, set of roles, set of shift types (3 multiselects)
- [ ] Preset shifts, list of:
    - Person
    - Week
    - Day
    - Shift type
    - Preference or absolute
    - Note: annual leave, day off requests, are implemented using these
- [ ] Personal shift patterns, for a particular person
    - Applies for a particular week or for a certain number of weeks
    - Shift pattern, list of: (count, shift type) pairs
- [ ] Weekly uniform shifts
    - Primary shift type (let’s call it P)
    - Compatible shift types (let’s call these C)
    - Semantics: if a shift of type P occurs in a week all other shifts must be from the set C
- [ ] Maximum shift count per week
    - Shift type (let’s call it P)
    - Maximum count (let’s call it c)
    - Semantics: there can be up to c occurrences of P in a week
- [ ] Continuity, a list of
    - Continuity from (shift type)
    - Continuity to (shift type)
    - Semantics: we count the number of shift pairs where from is followed by to and maximise the number of these
    - e.g. [(L, E), (E,E)]

**Comment by ozgurakgun** [comment]
> > Minimum number of people required for a selected set of teams, set of roles, set of shift types (3 multiselects)
> 
> Does this mean "there must be at least N people from team T / role R on shift S"? I.e. do we define these one by one or can there be multiple shifts and multiple teams/roles in one rule? (Anf if so, what does this mean?)

Sorry didn't notice this!

Each constraint has a set of teams, roles, and shift types.

The datatype is something like [(set of team, set of role, set of shift type, min_count)]

Does that make sense?

**Comment by gskorokhod** [comment]
![Image](https://github.com/user-attachments/assets/5fc7b58c-fc9c-483a-901a-edadea49fc32)

![Image](https://github.com/user-attachments/assets/4e85ca58-2e82-4b9e-a085-a7f85073c0cf)

![Image](https://github.com/user-attachments/assets/85784a10-dba5-4aa4-ab03-a7ff37a66a5e)

Generic labels UI is done! Just need to update all the remaining UI code to display them properly and I'll make a PR

**Comment by gskorokhod** [comment]
Assignment table (i.e. preset shifts for people) is done!

![Image](https://github.com/user-attachments/assets/7014047b-8ace-4bf9-93e2-ea2ab4288c5a)

![Image](https://github.com/user-attachments/assets/245dd5fe-ee98-4ceb-bea8-5dd2d4414785)

**Comment by ozgurakgun** [comment]
Not sure what you are referring to with the assignment table - is that not how we display solutions?

This is for input. On the calendar, every staff member should be able to say "I want a certain shift type for a given day/time, and this is a preference or requirement". Preference basically means we will make this assignment if possible, requirement is a hard-constraint.

Remember the one check mark / two check marks UI we considered for this? [This demo](https://conjure-cp.github.io/university-timetabling-demo/) uses it. Something like that could work, but I am  happy to hear alternative ideas too.

**Comment by ozgurakgun** [comment]
I see the assignment table now! It looks relevant, definitely. We can talk tomorrow.

**Comment by gskorokhod** [comment]
> Remember the one check mark / two check marks UI we considered for this? [This demo](https://conjure-cp.github.io/university-timetabling-demo/) uses it. Something like that could work, but I am happy to hear alternative ideas too.

Oh, I forgot about that - this may be better long term (although we'd need to think about how to combine it with selecting different shift types in a way that's intuitive), but for now I've added a checkbox to distinguish hard and soft assignments!

(the underlying type for this is an enum though so extending it would just be a matter of UI!)

**Comment by gskorokhod** [comment]
![Image](https://github.com/user-attachments/assets/b0e980ee-62d5-4c8a-9dd3-86bce025f575)

Here is the current UI

**Comment by ozgurakgun** [comment]
the current UI looks good, forget the single/double check marks :)
